# User configuration sourced by interactive shells

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi


# aliases

alias o="open"
alias g="ag --path-to-ignore=~/.agignore"
alias e="emacsclient -n"


export PATH=/Users/jetmind/.local/bin:"${PATH}"


# Swift configuration

export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"


# OPAM configuration
. /Users/jetmind/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true


# Go
export GOPATH=$HOME/p/go
